version: "3.1"
name: dune_odin

services:
  dune_odin:
    container_name: dune_odin
    image: registry.diikstra.fr/dune_odin:${IMAGE_TAG}
    restart: always
    ports:
      - 3001:3000
    environment:
      - API_URL=https://api.meledio.com
      - MEDIA_URL=https://media.meledio.com

networks:
  default:
    name: docker_default